### ISSUE TITLE
configuring letsencrypt certificate

### ISSUE THREAD

**Issue by zstanecic** [jmdaweb/NVDARemoteServer#49] opened 2023-02-24 15:40 UTC
Hi,
This is rather question, than issue, but it is very important one:
how i can connect lets encrypt certificate to be used as the NVDA remote server certificate, as it is trusted?
Best,
Zvonimir

**Comment by blindgeek** [comment] 2023-02-24 15:44
Is your server also warning upon connection that the certificate is not trusted hence this question? If so I have the same issue so I'm following this thread.

From: Zvonimir Stanečić ***@***.***>
Sent: Friday, February 24, 2023 11:41 PM
To: jmdaweb/NVDARemoteServer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jmdaweb/NVDARemoteServer] configuring letsencrypt certificate (Issue #49)


Hi,
This is rather question, than issue, but it is very important one:
how i can connect lets encrypt certificate to be used as the NVDA remote server certificate, as it is trusted?
Best,
Zvonimir

-

**Comment by jmdaweb** [comment] 2023-02-24 15:47
Hi,
You can use certfile and keyfile options. Set keyfile to /etc/letsencrypt/live/yourdomain/privkey.pem, and certfile to /etc/letsencrypt/live/yourdomain/fullchain.pem. Important using fullchain instead of chain or cert, because this one contains your certificate and the CA certificate in the same file.
If it doesn't work, let me know.
Regards.

**Comment by zstanecic** [comment] 2023-02-24 15:53
Hi,

It doesn’t work, unfortunatelly.

It refuses to start with it, and i cannot connect

● NVDARemoteServer.service - NVDARemote relay server                                                                    

     Loaded: loaded (/lib/systemd/system/NVDARemoteServer.service; enabled; preset: enabled)                            

     Active: active (running) since Fri 2023-02-24 15:50:48 UTC; 1min 50s ago                                           

    Process: 1416 ExecStart=/usr/bin/python3 /usr/share/NVDARemoteServer/server.py start (code=exited, status=0/SUCCESS)

   Main PID: 1420 (python3)                                                                                             

      Tasks: 3 (limit: 9291)                                                                                            

     Memory: 8.6M                                                                                                       

        CPU: 1.067s                                                                                                     

     CGroup: /system.slice/NVDARemoteServer.service                                                                     

             └─1420 /usr/bin/python3 /usr/share/NVDARemoteServer/server.py start                                        

                                                                                                                        

lut 24 15:50:48 vps-ae0ad7be systemd[1]: Starting NVDARemoteServer.service - NVDARemote relay server...                 

lut 24 15:50:48 vps-ae0ad7be systemd[1]: NVDARemoteServer.service: Supervising process 1420 which is not our child. We'>

lut 24 15:50:48 vps-ae0ad7be systemd[1]: Started NVDARemoteServer.service - NVDARemote relay server.                    

lines 1-14/14 (END

**Comment by jmdaweb** [comment] 2023-02-24 15:55
Can you paste the log contents? /var/log/NVDARemoteServer.log

**Comment by zstanecic** [comment] 2023-02-24 15:58
GNU nano 5.4                                  /var/log/NVDARemoteServer.log

Logging system initialized.

Fri Feb 24 15:50:48 2023

Configuring signal handlers

Fri Feb 24 15:50:48 2023

Initialized instance variables

Fri Feb 24 15:50:48 2023

IPV6 socket created.

Fri Feb 24 15:50:48 2023

Setting socket options...

Fri Feb 24 15:50:48 2023

IPV6 socket has started listening on port 6837

Fri Feb 24 15:50:48 2023

IPV4 socket created.

Fri Feb 24 15:50:48 2023

Setting socket options...

Fri Feb 24 15:50:48 2023

IPV4 socket cannot process incoming connections with the specified configuration. In most situations, this means IPV6 s>Fri Feb 24 15:50:48 2023

NVDA Remote Server is ready.

Fri Feb 24 15:50:48 2023

The server is running with pid 1420

Fri Feb 24 15:50:59 2023

New incoming connection from address ::ffff:213.190.26.153, port 61090

Fri Feb 24 15:50:59 2023

SSL negotiation failed.

Fri Feb 24 15:53:59 2023

 

^G Help        ^O Zapisz      ^W Wyszukaj    ^K Cut         ^T Execute     ^C Location    M-U Odwołaj    M-A Set Mark

^X Wyjdź       ^R Wczyt.plik  ^\ Zastąp      ^U Paste       ^J Wyjustuj    ^_ Do linii    M-E Odtwórz    M-6 Copy

**Comment by jmdaweb** [comment] 2023-02-24 16:02
OK, we almost have the cause of the issue. I need to know what is below "SSL negotiation failed" line. You can use another tools instead of nano, such as cat (which displays the entire file in the terminal) or tail (which displays the last 10 lines by default). For example: tail /var/log/NVDARemoteServer.log

**Comment by tech10** [comment] 2023-02-24 16:20
For anyone following this thread, I was able to use a Let's Encrypt certificate on my own server that I wrote. The NVDARemote addon continued to prompt to accept the fingerprint of the certificate, despite the fact that it was from a trusted certificate authority. I was even able to visit the server in my browser and receive no validation errors with the trusted certificate. Of course, nothing was displayed, but I received no alerts about an untrusted certificate.

@zstanecic Have you checked the file permissions of your Let's Encrypt certificate files, and the directories they're in? If any of the directories don't allow any permissions to read from any user, the file likely can't be opened by the server. This might not be the issue, but if it's not a file permission issue, that can at least be narrowed down.

**Comment by zstanecic** [comment] 2023-02-24 16:22
Hi, 

I have checked this, and al. Is ok there

**Comment by jmdaweb** [comment] 2023-02-24 16:25
I also remember something about Let's Encrypt and read permissions. Take into account that this server runs with an unprivileged account, but I need to confirm it.
If you are using the latest code from the repository, can you enable tracebacks on the config, restart the server and repeat the steps to reproduce the issue?

**Comment by zstanecic** [comment] 2023-02-24 16:27
Hi,

Yes, i can.

Let me do that

**Comment by zstanecic** [comment] 2023-02-24 16:29
New incoming connection from address ::ffff:213.190.26.153, port 61937                                                  

Fri Feb 24 16:28:41 2023                                                                                                

SSL negotiation failed.                                                                                                 

Fri Feb 24 16:28:41 2023                                                                                                

Traceback (most recent call last):                                                                                      

  File "/usr/share/NVDARemoteServer/server.py", line 288, in accept_new_connection                                      

    client_sock = ssl.wrap_socket(client_sock, keyfile=options.keyfile, certfile=options.certfile, server_side=True)    

  File "/usr/lib/python3.9/ssl.py", line 1402, in wrap_socket                                                           

    context.load_cert_chain(certfile, keyfile)                                                                          

PermissionError: [Errno 13] Permission denied

**Comment by jmdaweb** [comment] 2023-02-24 16:35
OK, so the problem is a permission error when reading the certificate files. This can be fixed in two ways:

* Copy the files to another location readable by the server. You will have to replace them every 3 months, after renewing.
* Use the chmod command to make the Let's Encrypt folders and files readable for all users: chmod -R 755 /etc/letsencrypt

This time, you don't need to restart the server. New certificates are handled dinamically each time a client opens a connection. For now, I don't know a more secure solution.

**Comment by tech10** [comment] 2023-02-24 16:40
This is a file permission issue.

If the permissions of any directory within the letsencrypt directory are rewd write execute for root only, then no other user or group can access the files. Here's an example from mine.

```console
$ ls -1al /etc/letsencrypt
total 40
drwxr-xr-x  9 root root 4096 Feb 24 00:47 .
drwxr-xr-x 51 root root 4096 Feb 24 05:42 ..
drwx------  3 root root 4096 Feb  9  2021 accounts
drwx------  3 root root 4096 Feb  9  2021 archive
drwxr-xr-x  2 root root 4096 Jan 31 12:38 csr
drwx------  2 root root 4096 Jan 31 12:38 keys
drwx------  3 root root 4096 Feb  9  2021 live
drwxr-xr-x  2 root root 4096 Jan 31 12:38 renewal
drwxr-xr-x  5 root root 4096 Feb  9  2021 renewal-hooks
-rw-r--r--  1 root root  424 Feb 10  2021 ssl-dhparams.pem
```

Take note that the keys and live directories both have the permissions drwx------ which means they are directories, the root user has read, write, and execute permissions, the root group has no permissions, and anyone else has no permissions. Thus, if I tried to list, read, write, or execute in any of those directories as any user that isn't root, it will fail.

@jmdaweb I wouldn't recommend your solution to chmod 755 on the letsencrypt directory, I would recommend the first solution, to copy the privkey.pem and fullchain.pem files to a directory of your choosing and alter their permissions to allow the public to read them, chmod to 644. You should be able to use hooks in the letsencrypt client to do this, or as part of a systemd service if you renew your certificates with that, and a timer.

Alternatively, you could chmod 755 on the letsencrypt/keys and letsencrypt/live directories, this should prevent anyone from accessing any sensative data related to your letsencrypt account and configuration files.

**Closed** 2023-07-19 18:32 UTC
