### ISSUE TITLE
error: SSL negotiation failed.

### ISSUE THREAD

**Issue by amirmahdifard** [jmdaweb/NVDARemoteServer#44] opened 2022-12-08 13:22 UTC
i'm running last vertion of nvda remote server in windows server as servis mode: this traceback sometimes stops my servis, randomly: so please fix it, it comes to my nvda remote.log
Thu Dec  8 02:12:57 2022
SSL negotiation failed.
Thu Dec  8 02:12:57 2022
Traceback (most recent call last):
  File "server.py", line 284, in accept_new_connection
  File "ssl.py", line 1441, in wrap_socket
  File "ssl.py", line 512, in wrap_socket
  File "ssl.py", line 1070, in _create
  File "ssl.py", line 1341, in do_handshake
ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:997)
please fix this: thanks:

**Comment by amirmahdifard** [comment] 2022-12-10 08:36
@jmdaweb what about this one, will you also fix this?

**Comment by jmdaweb** [comment] 2022-12-10 12:10
Of course, but I'm unable to reproduce it. I don't know what causes exactly that error.

**Comment by amirmahdifard** [comment] 2022-12-10 16:02
@jmdawebit somewhere it says enabled ssl, and sometimes it gives this error instead of enabling it, i will try to figger it out more and will tell you i can help you, see, when people are connecting to remote

**Comment by amirmahdifard** [comment] 2022-12-10 16:03
oops, it's mest up my text lol

**Comment by jmdaweb** [comment] 2023-01-28 16:05
Duplicate of #41.

**Closed by jmdaweb** 2023-01-28 16:05 UTC
