### ISSUE TITLE
unknown traceback error that stops my servis from running

### ISSUE THREAD

**Issue by amirmahdifard** [jmdaweb/NVDARemoteServer#45] opened 2022-12-08 13:29 UTC
so this one is unknown, because at the first, it doesn't say anything and just starts with traceback, and when this happens, it's stopps my servis and i have to start it again: i'm using the last vertion as i said before
Thu Dec  8 05:51:26 2022
Traceback (most recent call last):
  File "server.py", line 333, in run
ValueError: file descriptor cannot be a negative integer (-1)
Thu Dec  8 05:51:26 2022
Traceback (most recent call last):
  File "server.py", line 235, in run
ValueError: file descriptor cannot be a negative integer (-1)
Closing logger thread...
that's how it comes to my log.

**Comment by amirmahdifard** [comment] 2022-12-08 17:10
@jmdaweb hello, do you have any idea to fix these tracebacks? thanks

**Comment by jmdaweb** [comment] 2022-12-09 18:29
Duplicate of #42

**Closed by jmdaweb** 2022-12-09 18:29 UTC
