### ISSUE TITLE
Server does not stay running on Debian 8 Jessie

### ISSUE THREAD

**Issue by mobeeniqbal** [jmdaweb/NVDARemoteServer#22] opened 2018-09-30 11:37 UTC
## Issue description.

I have done the  following to get version 1.8 installed and running on 2 separate debian fresh installs, but debian still refuses to automatically start the server on boot. I am executing all commands as root. Please note that the below procedure worked fine with previous server releases.

git clone https://github.com/jmdaweb/NVDARemoteServer.git

cd NVDARemoteServer/debian8 

sudo chmod +x build.sh 

sudo ./build.sh 

sudo dpkg -i nvda-remote-server_1.8.deb 

sudo NVDARemoteServer enable

## Result.

The server starts for a few minutes next time the machine restarts, but is then killed.

## Debug log output.

Loggin system initialized. 
Wed Sep 26 11:59:25 2018 
Configuring signal handlers 
Wed Sep 26 11:59:25 2018 
Initialized instance variables 
Wed Sep 26 11:59:25 2018 
Socket created. 
Wed Sep 26 11:59:25 2018 
Enabled ssl in socket. 
Wed Sep 26 11:59:25 2018 
Setting socket options... 
Wed Sep 26 11:59:25 2018 
IPV6 socket has started listening on port 6837 
Wed Sep 26 11:59:25 2018 
IPV4 socket has not been created 
Wed Sep 26 11:59:25 2018 
NVDA Remote Server is ready. 
Wed Sep 26 11:59:25 2018 
The server is using TLS v 1.2 
Wed Sep 26 11:59:25 2018 
The server is running with pid 451 
Wed Sep 26 12:00:54 2018 
Received system signal. Waiting for server stop. 
Wed Sep 26 12:01:25 2018 
Shuting down server... 
Wed Sep 26 12:01:25 2018 
Closing channels... 
Wed Sep 26 12:01:25 2018 
Disconnecting clients... 
Wed Sep 26 12:01:25 2018 
Closing server socket... 
Closing logger thread... 

## Things I've tried.

I have tried running the server in debug mode after restarting and it stays running. The log output is the same as above apart from the server being killed. If I run via /etc/rc.local in debug mode, it sometimes does not auto start, and yet when I run from a terminal after all services have loaded it stays running. Is there anything else I can try?

**Comment by mythral0** [comment] 2018-09-30 11:43
Hi, I am facing exactly the same issue on Stretch. As a workaround, I have to install the [ackage each time I reboot.
Previous version also worked fine for me.

**Comment by jmdaweb** [comment] 2018-09-30 11:50
Hello.
Did you update pidfile parameter in the config file? It must point to /var/run/NVDARemoteServer/NVDARemoteServer.pid. Otherwise, systemd tries to start the daemon, waits some time and, after that, kills the process because it doesn't find the pid file. I will add an upgrade note in the next release.
Please, confirm that it works. If it doesn't work, run NVDARemoteServer status and paste the output here.
Regards.

**Comment by mobeeniqbal** [comment] 2018-09-30 12:11
Hi.
The parameter is already set correctly. I am pasting status output below.

â— NVDARemoteServer.service - NVDARemote relay server
   Loaded: loaded (/lib/systemd/system/NVDARemoteServer.service; enabled)
   Active: failed (Result: resources) since Sun 2018-09-30 06:00:26 BST; 7h ago
  Process: 417 ExecStart=/usr/bin/python /usr/share/NVDARemoteServer/server.py start (code=exited, status=0/SUCCESS)

Sep 30 06:00:16 vps585906.ovh.net systemd[1]: PID file /var/run/NVDARemoteServer/NVDARemoteServer.pid not readable (yet?) after start.
Sep 30 06:00:26 vps585906.ovh.net systemd[1]: NVDARemoteServer.service never wrote its PID file. Failing.
Sep 30 06:00:26 vps585906.ovh.net systemd[1]: Failed to start NVDARemote relay server.
Sep 30 06:00:26 vps585906.ovh.net systemd[1]: Unit NVDARemoteServer.service entered failed state.

**Comment by jmdaweb** [comment] 2018-09-30 12:18
Hello.
Does the directory /var/run/NVDARemoteServer exist? If the answer is no, try creating it. Assign the ownership to NVDARemoteServer user account.

Quick solution to almost all problems: purge and reinstall.

sudo dpkg --purge nvda-remote-server
sudo dpkg -i nvda-remote-server-1.8.deb

If it doesn't work, build the package as root without using sudo, and cloning the repository in the root account.
Regards.

**Comment by mythral0** [comment] 2018-09-30 12:34
Hi,
Many thanks, works perfectly now.
I purged and reinstalled after changing the path in the config file.
KND RGS

Mo.

**Comment by mobeeniqbal** [comment] 2018-09-30 13:45
Hi. I'm reopening this as it's still not working for me. I have followed all suggestions. I have purged my install and made sure all config files are deleted. I have also disabled the NVDA service before purging. When I have rebuilt the package running all commands as root without sudo, the server installs fine and the PID file is created at /var/run/NVDARemoteServer/NVDARemoteServer.pid. I do NVDARemoteServer enable and a symlink is created. All good so far and the server is running. I then reboot and the server goes back to doing what it did before. I.E /var/run/NVDARemoteServer/NVDARemoteServer.pid does not exist at all. Even when I create the directory manually and restart, the directory is deleted on the next reboot. Can I perhaps change permissions so the folder can't be deleted? Or is it that the server is not meant to run as root?

**Comment by mobeeniqbal** [comment] 2018-09-30 14:00
Hi. Further to my previous comment. I could be wrong, but  the following thread on askubuntu seems to fit in with the current results I have. files are purged on reboot from /var/run. The server doesn't seem to recreate the directory/pid file that it needs.
https://askubuntu.com/questions/303120/how-folders-created-in-var-run-on-each-reboot

**Comment by jmdaweb** [comment] 2018-09-30 14:19
OK, I can reproduce this issue on my machines. I am fixing it.

**Comment by mythral0** [comment] 2018-09-30 17:06
Apologies chaps,
Yes, I still get the same problem when I reboot, I didn’t try rebooting last time. Many thanks.
Kind regards.

**Comment by jmdaweb** [comment] 2018-09-30 17:47
Hello.

Please, test the changes made in the systemd branch. Before building,
run git checkout systemd. You should clone, purge and reinstall again.

Regards.

**Comment by mobeeniqbal** [comment] 2018-09-30 18:32
Hello.

Appologies if this appears twice, having email issues. I found the command and managed to clone with:

git clone --single-branch -b systemd https://github.com/jmdaweb/NVDARemoteServer.git

I recompiled and the following errors are returned when running dpkg -i nvda-remote-server_1.8.deb.

Selecting previously unselected package nvda-remote-server.                     
(Reading database ... 37556 files and directories currently installed.)         
Preparing to unpack nvda-remote-server_1.8.deb ...                              
Unpacking nvda-remote-server (1.8-1) ...                                        
Setting up nvda-remote-server (1.8-1) ...                                       
/var/lib/dpkg/info/nvda-remote-server.postinst: line 7: systemd-sysusers: comman
d not found                                                                     
dpkg: error processing package nvda-remote-server (--install):                  
 subprocess installed post-installation script returned error exit status 127   
Processing triggers for man-db (2.7.0.2-5) ...                                  
Errors were encountered while processing:                                       
 nvda-remote-server                                                             

Kind Regards,

Mo.

**Comment by jmdaweb** [comment] 2018-09-30 19:15
OK, systemd-sysusers is available on Debian Stretch, but not in Jessie.
Please, test the latest commit on this branch.

Regards.

**Comment by mobeeniqbal** [comment] 2018-09-30 19:50
I have tested it on my test machine and it seems to be working. I want to leave it running for a few hours to see what it does. I will also test on my raspberry pi tomorrow and report back. I haven't got a machine running stretch to test with unfortunately, but it would be good to have it working for stretch also if any testers have a machine available. Please do not close the issue yet, I will be in touch later today/tomorrow.

Many thanks and Kind Regards.

**Comment by mobeeniqbal** [comment] 2018-09-30 21:12
Hi. The bug seems to be fixed for stretch and Jessie. I have had the server running on Jessie for over an hour with no issues so far touch wood. Many thanks for resolving this so promptly, if only all developers were this prompt. Changes can probably be commited to master and released as 1.9.
Kind Regards,
Mo.

**Comment by mobeeniqbal** [comment] 2018-09-30 21:13
PS: Forgot to mention that I did a fresh stretch install on a pi and tested and it seems to run fine. Git hub should allow editing of comments.
Kind Regards.

**Comment by mythral0** [comment] 2018-10-01 08:15
Hi, this is also working fine for me. I have restarted the machine many times and am able to start the service NVDARemoteServer start
Just one newbi question, how do I get the NVDARemoteServer service start automatically on bootup?
Many thanks.

KND RGS

Mo.

**Comment by mobeeniqbal** [comment] 2018-10-01 08:35
Hi. Type NVDARemoteServer enable to enable the service and disable to remove the service.
cheers,
Mo.

**Comment by mythral0** [comment] 2018-10-01 09:54
mobeeniqbal, Many thanks for that info, works like a charm.
Many thanks to you and Jose in getting this working so fast, truly amazing.
Many thanks.

KND RGS

Mo.

**Comment by jmdaweb** [comment] 2018-10-01 13:07
Hello.
Thank you very much for your feedback. The changes made in systemd branch have been merged into master, taking into account all supported Linux distributions. Now this issue can be closed.

**Closed by jmdaweb** 2018-10-01 13:07 UTC
